/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Dan Aronson' at '1/5/17 7:06 PM' with Gradle 2.14.1
 *
 * @author Dan Aronson, @date 1/5/17 7:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
